notification:
  sender: "pricetracker@example.com"
  recipients:
    - "user@example.com"

price_drop_threshold_pct: 10.0
snapshot_lookback: 5

items:
  - url: https://www.costco.ca/.product.4000092152.html
  - url: https://www.costco.ca/.product.100713037.html
  - url: https://www.costco.ca/.product.100946336.html
  - url: https://www.costco.ca/.product.4000151796.html
  - url: https://www.canadacomputers.com/en/powered-by-amd/267624/gigabyte-radeon-rx-9070-xt-gaming-oc-16g-graphics-card-gv-r9070xtgaming-oc-16gd-gv-r9070xtgaming-oc-16gd.html
